spring.application.name=server

logging.level.org.springframework.security=DEBUG

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true

# DATASOURCE - POSTGRESQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/e_learning}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10

#JWT
jwt.base64-secret=${JWT_BASE64_SECRET:tybBIQtqJWNdlTayWJmWt6v5xOoYq4W6g/iBY6XZp+aLRMNhwpXhvRth4nravWlrn5cVbWfwtUXshmnW7+ZjGg==}
jwt.access-token-expire=${JWT_ACCESS_TOKEN_EXPIRE:3600}
jwt.refresh-token-expire=${JWT_REFRESH_TOKEN_EXPIRE:604800}
jwt.cookie-secure=${JWT_COOKIE_SECURE:true}
