"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowDown, ArrowUp, BookOpen } from "lucide-react";
import { contentService } from "@/services/content.service";
import { QUERY_KEYS } from "@/services/query-keys";
import type { ContentView, CreateSectionRequest } from "@/types/content";
import { EntityHeader } from "./components/entity-header";
import { Badge } from "./components/badge";
import { TableTitle } from "./components/table-title";

export function UnitDetail({ unitId, onNavigate }: { unitId: number; onNavigate: (view: ContentView, id?: number) => void }) {
  const client = useQueryClient(); const [formOpen, setFormOpen] = useState(false); const [name, setName] = useState(""); const [description, setDescription] = useState("");
  const unit = useQuery({ queryKey: QUERY_KEYS.contentUnit(unitId), queryFn: async () => (await contentService.getUnit(unitId)).data });
  const sections = useQuery({ queryKey: QUERY_KEYS.contentSections(unitId), queryFn: async () => (await contentService.listSections(unitId)).data });
  const create = useMutation({ mutationFn: contentService.createSection, onSuccess: () => { client.invalidateQueries({ queryKey: QUERY_KEYS.contentSections(unitId) }); setFormOpen(false); setName(""); setDescription(""); } });
  const archive = useMutation({ mutationFn: contentService.archiveSection, onSuccess: () => client.invalidateQueries({ queryKey: QUERY_KEYS.contentSections(unitId) }) });
  const move = (index: number, direction: -1 | 1) => { const items = [...(sections.data ?? [])]; const target = index + direction; if (target < 0 || target >= items.length) return; [items[index], items[target]] = [items[target], items[index]]; /* reorder endpoint will be enabled with the next backend slice */ };
  if (unit.isLoading) return <p className="text-sm text-slate-400">Loading unit...</p>;
  if (unit.isError || !unit.data) return <p className="rounded bg-rose-50 p-4 text-sm text-rose-600">Could not load unit.</p>;
  return <><EntityHeader title={`${unit.data.code} - ${unit.data.name}`} label={`Grade ${unit.data.gradeId}`} description={unit.data.description ?? "Organize learning content for this unit."} icon={<BookOpen size={21} />} editLabel="Edit Unit" /><section className="rounded-lg border border-slate-200 bg-white p-4"><TableTitle title="Sections" count={sections.data?.length ?? 0} action="Add Section" onAction={() => setFormOpen(true)} />{formOpen && <form className="mb-4 flex flex-wrap gap-2 rounded bg-primary-light p-3" onSubmit={(event) => { event.preventDefault(); const payload: CreateSectionRequest = { unitId, name, description }; create.mutate(payload); }}><input required autoFocus placeholder="Section name" value={name} onChange={(event) => setName(event.target.value)} className="min-w-[180px] flex-1 rounded border px-2 py-2 text-sm" /><input placeholder="Description" value={description} onChange={(event) => setDescription(event.target.value)} className="min-w-[220px] flex-1 rounded border px-2 py-2 text-sm" /><button disabled={create.isPending} className="rounded bg-primary px-3 py-2 text-sm text-white">{create.isPending ? "Saving..." : "Save"}</button><button type="button" onClick={() => setFormOpen(false)} className="rounded border bg-white px-3 py-2 text-sm">Cancel</button></form>}<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="bg-slate-50 text-left text-slate-500"><th className="p-2.5">#</th><th className="p-2.5">Section</th><th className="p-2.5">Topics</th><th className="p-2.5">Status</th><th className="p-2.5">Actions</th></tr></thead><tbody>{sections.data?.map((section, index) => <tr key={section.id} className="border-b border-slate-100 hover:bg-primary-light/30"><td className="p-2.5 text-slate-400">{index + 1}</td><td className="p-2.5"><button className="font-semibold hover:text-primary" onClick={() => onNavigate("section", section.id)}>{section.name}</button></td><td className="p-2.5 text-slate-500">{section.totalTopic}</td><td className="p-2.5"><Badge>{section.status}</Badge></td><td className="p-2.5"><div className="flex gap-1"><button disabled={index === 0} onClick={() => move(index, -1)} aria-label="Move up" className="rounded border p-1 disabled:opacity-30"><ArrowUp size={14} /></button><button disabled={index === (sections.data?.length ?? 0) - 1} onClick={() => move(index, 1)} aria-label="Move down" className="rounded border p-1 disabled:opacity-30"><ArrowDown size={14} /></button><button onClick={() => archive.mutate(section.id)} className="rounded border px-2 py-1 text-xs text-rose-500">Archive</button></div></td></tr>)}</tbody></table></div></section></>;
}
